name: Build Installer Asset

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.3
      with:
        sparse-checkout: hangman

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.12'

    - name: Install linters
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 mypy

    - name: Run Linters
      id: lint
      run: |
        pylint hangman/*.py
        pylint_status=$?
        flake8 hangman
        flake8_status=$?
        mypy hangman
        mypy_status=$?

    - name: Check Linting Results
      run: |
        if [ $pylint_status -ne 0 ] || [ $flake8_status -ne 0 ] || [ $mypy_status -ne 0 ]; then
          echo "Linting failed. Exiting..."
          exit 1
        else
          echo "Linting succeeded."
        fi

    - name: Install makeself
      run: |
        # sudo apt-get update
        sudo apt-get install makeself

    - name: Build Installer
      run: |
        chmod +x hangman/install_script.sh
        makeself --sha256 hangman/ hangman_installer.run "Hangman-CLI installer" ./install_script.sh
        chmod +x hangman_installer.run

    - name: Tar files
      run: tar -cvf hangman_installer.tar hangman_installer.run

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v3
      with:
        name: hangman_installer
        path: hangman_installer.tar
        if-no-files-found: error

    - name: Upload Py Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hangman-cli
        path: hangman/**/*.py
