name: Build and Release Installer

on:
  workflow_dispatch:
  # push:
    # branches:
      # - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        sparse-checkout: hangman

    - name: Install makeself
      run: |
        sudo apt update
        sudo apt install makeself

    - name: Build Installer
      run: |
        chmod +x hangman/install_script.sh
        makeself --sha256 hangman/ hangman_installer.run "Hangman-CLI installer" ./install_script.sh

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v3
      with:
        name: hangman_installer
        path: hangman_installer.run
        if-no-files-found: error
